version: "3.1"
services:

  avito:
    image: avito-balance-api
    container_name: balance-api-container
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - postgresdb
    restart: always


  postgresdb:
    container_name: abitodb
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: avitodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx