version: "3.1"
services:

  postgresdb:
    container_name: abitodb
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: avitodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx